export const StoreProduct=[
    {
        id: 1,
        name:"Sumsung Note-5",
        img:"/images/first.jpg",
        company:"Sumsug-Company",
        info:
         "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit", 
         price:12.90,
        inCart:false,
        count:0,
        total:0,
    },
    {
        id: 2,
        name:"Sumsung Galaxy-s4",
        img:"/images/second.jpg",
        company:"Sumsug-Company",
        info:
         "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit", 
         price:14.90,
        inCart:false,
        count:0,
        total:0,
    },
    {
        id: 3,
        name:"Sumsung Note-5",
        img:"/images/third.jpg",
        company:"Sumsug-Company",
        info:
         "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit", 
         price:12,
        inCart:false,
        count:0,
        total:0,
    },
    {
        id: 4,
        name:"Sumsung Note-5",
        img:"images/first.jpg",
        company:"Sumsug-Company",
        info:
         "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit", 
         price:12,

        inCart:true,
        count:0,
        total:0,
    },
    {
        id: 5,
        name:"Sumsung Note-5",
        img:"images/first.jpg",
        company:"Sumsug-Company",
        info:
         "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit", 
         price:12,
        inCart:false,
        count:0,
        total:0,
    },
     {
         id: 6,
         name: "Sumsung Note-5",
         img: "images/first.jpg",
         company: "Sumsug-Company",
         info: "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit",
         price: 12,
         inCart: true,
         count: 0,
         total: 0,
     },
      {
          id: 7,
          name: "Sumsung Note-5",
          img: "images/first.jpg",
          company: "Sumsug-Company",
          info: "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit",
          price: 12,
          inCart: true,
          count: 0,
          total: 0,
      },
       {
           id: 8,
           name: "Sumsung Note-5",
           img: "images/first.jpg",
           company: "Sumsug-Company",
           info: "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit",
           price: 12,
           inCart: false ,
           count: 0,
           total: 0,
       },
        {
            id: 9,
            name: "Sumsung Note-5",
            img: "images/first.jpg",
            company: "Sumsug-Company",
            info: "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit",
            price: 12,
            inCart: false,
            count: 0,
            total: 0,
        },
    ];
    export const detailProduct={
            id: 9,
             name: "Sumsung Note-5",
             img: "images/first.jpg",
             company: "Sumsug-Company",
             info: "The phone was produced by the sumsumg compan which has the lastest features all users are going to love beyond all imagination and prouduction limit",
             price: 12,
             inCart:false,
             count: 0,
             total: 0,
    }
